management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
ratelimit.refresh.ms=300000
management.metrics.tags.application=rate-limiter

spring.datasource.url=jdbc:mysql://localhost:3306/ratelimit
spring.datasource.username=root
spring.datasource.password=mysql123
spring.jpa.hibernate.ddl-auto=none